services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest # <- update image version here, see: https://github.com/AdguardTeam/AdGuardHome
    hostname: adguard.local
    depends_on:
      - unbound
    restart: always
    deploy:
      resources: # <- these settings are optional, but can help to limit resource reservations
        limits:
          memory: 768M
        reservations:
          memory: 256M
    ports:
      # DNS Ports
      - 53/tcp
      - 53/udp
      # DHCP
      - 67/udp
      # Dashboard
      - 3000/tcp # first setup
      - 80/tcp # web ui -> http://10.0.0.225/admin
# RECOMMENDED: Uncomment and adapt if you want to persist pihole configurations after restart
    volumes:
      - /mnt/fast/app-config/adguard-home/data:/opt/adguardhome/work
      - /mnt/fast/app-config/adguard-home/config:/opt/adguardhome/conf
    networks:
      dnsvlan:
        ipv4_address: 10.0.0.225 # <-- use this ip as dns when connected to pihole_dns_network (i.e. within a docker network)
  
  unbound:
    build: ./unbound
    container_name: unbound
    hostname: unbound.local
    restart: unless-stopped
    ports:
      - "5335:53/tcp" # expose a different port (5335) so you can use it directly
      - "5335:53/udp"
    networks:
      dnsvlan:
        ipv4_address: 10.0.0.224 # <-- this is used by pihole as upstream DNS

networks:
  # Define a custom subnet for pihole so that unbound can be an upstream DNS on port 53
  dnsvlan:
    name: dnsvlan
    driver: macvlan
    driver_opts:
      parent: eno1                        # If open vSwitch is enabled use ovs_eth0 (or ovs_eth1 etc.)
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
          ip_range: 10.0.0.224/30 # 10.0.0.224 - 10.0.0.225
